name: Test and Lint

on:
  pull_request:
    types:
      - opened
      - synchronize 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
      # Check out the repository code to the GitHub runner.
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
      # Set up the specified Python version.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pylint
        pip install pytest
      # Install the necessary dependencies for the project.
    - name: Analysing the code with pytest
      run: |
        pytest tests/test_hello.py
      # Run tests using pytest.
    - name: Analysing the code with pylint
      run: |
        pylint --disable=W0621 $(git ls-files '*.py')
      # Run pylint to analyze the code and check for coding standards.
